/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ArtigoSlugRouteImport } from './routes/artigo.$slug'

const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigoSlugRoute = ArtigoSlugRouteImport.update({
  id: '/artigo/$slug',
  path: '/artigo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/pesquisa': typeof PesquisaRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/pesquisa': typeof PesquisaRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/pesquisa': typeof PesquisaRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/pesquisa'
    | '/artigo/$slug'
    | '/auth/callback'
    | '/auth/logout'
    | '/categoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/pesquisa'
    | '/artigo/$slug'
    | '/auth/callback'
    | '/auth/logout'
    | '/categoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/pesquisa'
    | '/artigo/$slug'
    | '/auth/callback'
    | '/auth/logout'
    | '/categoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  PesquisaRoute: typeof PesquisaRoute
  ArtigoSlugRoute: typeof ArtigoSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigo/$slug': {
      id: '/artigo/$slug'
      path: '/artigo/$slug'
      fullPath: '/artigo/$slug'
      preLoaderRoute: typeof ArtigoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  PesquisaRoute: PesquisaRoute,
  ArtigoSlugRoute: ArtigoSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
